# Generated by Django 5.2.17 on 2026-09-09 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaxonomyAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'taxonomy_attributes',
            },
        ),
        migrations.CreateModel(
            name='TaxonomyCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('full_name', models.TextField(blank=True)),
                ('level', models.PositiveIntegerField(default=0)),
                ('is_leaf', models.BooleanField(default=False)),
                ('is_root', models.BooleanField(default=False)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='taxonomy.taxonomycategory')),
            ],
            options={
                'db_table': 'taxonomy_categories',
            },
        ),
        migrations.CreateModel(
            name='CategoryAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='taxonomy.taxonomyattribute')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='taxonomy.taxonomycategory')),
            ],
            options={
                'db_table': 'category_attributes',
            },
        ),
        migrations.CreateModel(
            name='TaxonomyAttributeValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='taxonomy.taxonomyattribute')),
            ],
            options={
                'db_table': 'taxonomy_attribute_values',
                'indexes': [models.Index(fields=['attribute'], name='taxonomy_at_attribu_3417e9_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='taxonomycategory',
            index=models.Index(fields=['parent'], name='taxonomy_ca_parent__d74e32_idx'),
        ),
        migrations.AddIndex(
            model_name='taxonomycategory',
            index=models.Index(fields=['name'], name='taxonomy_ca_name_9c07a7_idx'),
        ),
        migrations.AddConstraint(
            model_name='categoryattribute',
            constraint=models.UniqueConstraint(fields=('category', 'attribute'), name='unique_category_attribute'),
        ),
    ]
