# Generated by Django 5.2.17 on 2026-09-09 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('taxonomy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confidence', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('REVIEW', 'Manual Review'), ('FAILED', 'Failed'), ('APPROVED', 'Approved')], default='PENDING', max_length=20)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classifications', to='taxonomy.taxonomycategory')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classifications', to='products.product')),
            ],
            options={
                'db_table': 'classifications',
            },
        ),
        migrations.CreateModel(
            name='ClassificationAlternative',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confidence', models.DecimalField(decimal_places=4, max_digits=5)),
                ('rank', models.PositiveIntegerField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taxonomy.taxonomycategory')),
                ('classification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alternatives', to='classification.classification')),
            ],
            options={
                'db_table': 'classification_alternatives',
                'ordering': ['rank'],
            },
        ),
        migrations.CreateModel(
            name='ProductAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confidence', models.DecimalField(decimal_places=4, max_digits=5)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taxonomy.taxonomyattribute')),
                ('classification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='classification.classification')),
                ('value', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='taxonomy.taxonomyattributevalue')),
            ],
            options={
                'db_table': 'product_attributes',
            },
        ),
        migrations.AddIndex(
            model_name='classification',
            index=models.Index(fields=['product'], name='classificat_product_09a9fb_idx'),
        ),
        migrations.AddIndex(
            model_name='classification',
            index=models.Index(fields=['status'], name='classificat_status_977b0a_idx'),
        ),
    ]
