# Generated by Django 5.2.17 on 2026-09-09 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductBatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('total_products', models.PositiveIntegerField(default=0)),
                ('processed_products', models.PositiveIntegerField(default=0)),
                ('failed_products', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'product_batches',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_number', models.CharField(max_length=255, unique=True)),
                ('model_number', models.CharField(blank=True, max_length=255)),
                ('product_category', models.CharField(blank=True, max_length=255)),
                ('product_sub_category', models.CharField(blank=True, max_length=255)),
                ('collection_name', models.CharField(blank=True, max_length=255)),
                ('color_collection', models.CharField(blank=True, max_length=255)),
                ('product_color', models.CharField(blank=True, max_length=255)),
                ('product_name', models.CharField(max_length=500)),
                ('product_description', models.TextField(blank=True)),
                ('bullets', models.TextField(blank=True)),
                ('set_includes', models.TextField(blank=True)),
                ('materials', models.TextField(blank=True)),
                ('product_dimensions', models.CharField(blank=True, max_length=500)),
                ('product_weight', models.CharField(blank=True, max_length=255)),
                ('assembly_required', models.BooleanField(blank=True)),
                ('is_set', models.BooleanField(blank=True)),
                ('stackable', models.BooleanField(blank=True)),
                ('country_of_origin', models.CharField(blank=True, max_length=255)),
                ('image_urls', models.JSONField(blank=True, default=list)),
                ('product_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'products',
                'indexes': [models.Index(fields=['model_number'], name='products_model_n_dba756_idx'), models.Index(fields=['product_category'], name='products_product_449a4e_idx'), models.Index(fields=['product_sub_category'], name='products_product_5e0ee2_idx')],
            },
        ),
    ]
